# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:

- env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
    - amd64
  hooks:
    post: upx dist/linux_amd64/crypto-price

archive:
  name_template: "{{ .Binary }}"
  files:
  - none*
  format: binary
  replacements:
    linux: Linux
    386: i386
    amd64: x86_64

sign:
  artifacts: checksum
  args: ["-u", "BA82 F255 79A8 8012 C317  202F 1444 7AF3 CE37 622B", "--output", "${signature}", "--detach-sign", "${artifact}"]

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  github:
    owner: u3mur4
    name: crypto-price
  draft: true
  prerelease: false

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
